name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo test --verbose -- --ignored
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo rustdoc --verbose -- --html-in-header rustdoc-include-katex-header.html
        env:
          RUSTDOCFLAGS: -Dwarnings
